### ISSUE TITLE
[feature request] Enabling CI build (AppVeyor) and static analyzers (QC+Landscape)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [enthought/comtypes#106]
This is my first relatively successful attempt to enable AppVeyor build ([1.1.3build3](https://ci.appveyor.com/project/pywinauto/comtypes/build/1.1.3build3)) on 8 Pythons. AppVeyor uses `Windows Server 2012 R2 (x64)`.

The results are not bad for Py2.7, but require some attention.
```
Ran 96 tests in 59.926s (10 modules skipped)
Unavailable resources: CRASHES, devel, events, memleaks, pythoncom, time, typelibs, ui
 
FAILED (failures=4)
```

Python 3.x tests completely fail (looks like not so hard to fix).
```
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    dist = setup(**setup_params)
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 66, in run
    self.refcounts)
  File "build\lib\comtypes\test\__init__.py", line 190, in run_tests
    skipped, testcases = get_tests(package, mask, verbosity)
  File "build\lib\comtypes\test\__init__.py", line 89, in get_tests
    for modname in find_package_modules(package, mask):
  File "build\lib\comtypes\test\__init__.py", line 76, in find_package_modules
    for fnm in package.__loader__._files.keys():
AttributeError: 'SourceFileLoader' object has no attribute '_files'
```

Static code analyzers might also be useful for the project.
* [Landscape.io health check](https://landscape.io/github/vasily-v-ryabov/comtypes/1) (done on Py3)
* [Quantified Code issues](https://www.quantifiedcode.com/app/project/gh:vasily-v-ryabov:comtypes)

**Comment by cfarrow** [comment]
Sorry for taking so long to get back about this. My time to work on this project is very limited, but I don't want to stand in the way of good contributions or suggestions. If you would like push rights to this repo so it is easier to add patches, please let me know.

**Comment by vasily-v-ryabov** [comment]
Currently I'm too busy with my students, but I hope to make some contributions this summer. I will check later if push rights are necessary for AppVeyor integration and will let you know.

**Comment by junkmd** [comment]
@vasily-v-ryabov 
@cfarrow 

http://landscape.io/ and https://www.quantifiedcode.com/ are not working currently.

What about this issue?

**Comment by vasily-v-ryabov** [comment]
Landscape and Quantified Code are dead. There is [Codacy](https://app.codacy.com/organizations) which requires to authorize organization first. Another service LGTM is shutting down in December, 2022 so it doesn't make sense to enable it old way, but they became a part of GitHub: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by vasily-v-ryabov** [comment]
PR https://github.com/pywinauto/pywinauto/pull/1255 enables CodeQL instead of LGTM. `comtypes` needs something similar.
