### ISSUE TITLE
Syntax error on Python 3.5 ( True=1 )

### ISSUE THREAD

**Issue by janbrohl** [enthought/comtypes#108]
I get a syntax error in generated code on Python 3.5 64bit, windows 10 (64 bits) with the traceback below (full session).

```
C:\Users\Jan\Desktop\testpy>py -3 -m venv env1

C:\Users\Jan\Desktop\testpy>env1\Scripts\pip install pywebview
Collecting pywebview
  Downloading pywebview-1.1.tar.gz
Collecting comtypes (from pywebview)
  Downloading comtypes-1.1.2.zip (179kB)
    100% |################################| 180kB 795kB/s
Collecting pypiwin32 (from pywebview)
  Downloading pypiwin32-219-cp35-none-win_amd64.whl (8.6MB)
    100% |################################| 8.6MB 37kB/s
Installing collected packages: comtypes, pypiwin32, pywebview
  Running setup.py install for comtypes
  Running setup.py install for pywebview
Successfully installed comtypes-1.1.2 pypiwin32-219 pywebview-1.1
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Jan\Desktop\testpy>env1\Scripts\python.exe
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import webview
>>> webview.create_window("Simple browser", "http://www.flowrl.com", width=800, height=600, resizable=False)
# Generating comtypes.gen._EAB22AC0_30C1_11CF_A7EB_0000C05BAE0B_0_1_1
# Generating comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0
# Generating comtypes.gen.stdole
# Generating comtypes.gen.SHDocVw
# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 110, in error_printer
    return func(self, this, *args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in IDispatch_Invoke
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in <listcomp>
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\automation.py", line 428, in _get_value
    return ptr.__ctypes_from_outparam__()
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 113712
    True = 1
           ^
SyntaxError: can't assign to keyword
ERROR:comtypes._comobject:Exception in IDispatch.Invoke implementation:
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 76, in call_with_this
    result = mth(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 110, in error_printer
    return func(self, this, *args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in IDispatch_Invoke
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in <listcomp>
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\automation.py", line 428, in _get_value
    return ptr.__ctypes_from_outparam__()
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 113712
    True = 1
           ^
SyntaxError: can't assign to keyword
# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 111590
    True = 1
           ^
SyntaxError: can't assign to keyword
ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 147, in call_without_this
    result = mth(*inargs)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 111590
    True = 1
           ^
SyntaxError: can't assign to keyword
# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 110, in error_printer
    return func(self, this, *args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in IDispatch_Invoke
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in <listcomp>
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\automation.py", line 428, in _get_value
    return ptr.__ctypes_from_outparam__()
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 42319
    True = 1
           ^
SyntaxError: can't assign to keyword
ERROR:comtypes._comobject:Exception in IDispatch.Invoke implementation:
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 76, in call_with_this
    result = mth(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 110, in error_printer
    return func(self, this, *args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in IDispatch_Invoke
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 763, in <listcomp>
    args = [params.rgvarg[i].value for i in indexes]
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\automation.py", line 428, in _get_value
    return ptr.__ctypes_from_outparam__()
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 42319
    True = 1
           ^
SyntaxError: can't assign to keyword
# Generating comtypes.gen._3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 34212
    True = 1
           ^
SyntaxError: can't assign to keyword
ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\_comobject.py", line 147, in call_without_this
    result = mth(*inargs)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_events.py", line 117, in error_printer
    return func(*args, **kw)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\webview\win32.py", line 273, in DocumentComplete
    custom_doc = self.browser.Document.QueryInterface(ICustomDoc)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 44, in wrap_outparam
    return GetBestInterface(punk)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\client\_generate.py", line 26, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\gen\_3050F1C5_98B5_11CF_BB82_00AA00BDCE0B_0_4_0.py", line 34212
    True = 1
           ^
SyntaxError: can't assign to keyword
>>>
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\testpy\env1\lib\site-packages\comtypes\__init__.py", line 192, in shutdown
    _cominterface_meta._com_shutting_down = True
KeyboardInterrupt

C:\Users\Jan\Desktop\testpy>
```

**Comment by pushrbx** [comment]
Same on 3.4.3

**Comment by parryc** [comment]
See this issue https://github.com/enthought/comtypes/issues/92

You can install the latest dev version, which has the fix, by running `pip install --upgrade https://github.com/enthought/comtypes/tarball/master`.

**Comment by takluyver** [comment]
@cfarrow @jaraco - any chance of a new release containing the fix that was already merged for this?

**Comment by cfarrow** [comment]
I made a release. Thanks for the reminder.

**Comment by takluyver** [comment]
Thanks :-)

**Comment by takluyver** [comment]
This issue can probably be closed, then.

**Comment by alsoeric** [comment]
```
PS C:\Users\eric\AppData\Local\Programs\Python\Python35\Scripts> .\pip3.5.exe search comtypes
comtypes (1.1.3)  - Pure Python COM package
  INSTALLED: 1.1.2
  LATEST:    1.1.3
```
I can't seem to upgrade to 1.1.3.  is the release published correctly?

**Comment by vasily-v-ryabov** [comment]
Have the same problem for Python 2.7 though it's not annoying for me. :)

**Comment by cfarrow** [comment]
I can't download 1.1.3 either. I'm working on a fix.

**Comment by cfarrow** [comment]
I've got it working now (at least for me). Please give it a try.

**Comment by alsoeric** [comment]
it works.  
`
Collecting comtypes
  Downloading comtypes-1.1.3-2.zip (179kB)
    100% |################################| 184kB 1.5MB/s
Installing collected packages: comtypes
  Running setup.py install for comtypes ... done
Successfully installed comtypes-1.1.3
'

**Comment by vasily-v-ryabov** [comment]
It works for me too. Thanks!
