### ISSUE TITLE
Error using comtypes.client to convert a .pptx file into .pdf

### ISSUE THREAD

**Issue by keshrath** [enthought/comtypes#129]
I'm trying to convert a .pptx file to a pdf file. So far I got:
```
PP_FORMAT_PDF = 32

...

def _convert_powerpoint2pdf(input_path, output_path):
    try:
        import comtypes
        import comtypes.client
    except ImportError as error:
        raise 
    else:
        powerpoint = slides = None
        try:
            comtypes.CoInitialize()
            powerpoint = comtypes.client.CreateObject('Powerpoint.Application')
            slides = powerpoint.Presentations.Open(input_path)
            slides.SaveAs(output_path, FileFormat=PP_FORMAT_PDF)
        except WindowsError as error:
            raise
        except comtypes.COMError as error:
            raise IOError(error)
        finally:
            slides and slides.Close()
            powerpoint and powerpoint.Quit()
            comtypes.CoUninitialize()
```
Error:
```
Traceback (most recent call last):
  File "C:/Users/Mathias/git/pdfconv/tests\test_converter.py", line 89, in test_convert_presentation2pdf_pptx
    pdfconv.converter.convert_presentation2pdf(input_path, output_path)
  File "c:\users\mathias\git\pdfconv\pdfconv\converter.py", line 116, in convert_presentation2pdf
    _convert_powerpoint2pdf(input_path, output_path)
  File "c:\users\mathias\git\pdfconv\pdfconv\converter.py", line 179, in _convert_powerpoint2pdf
    slides.SaveAs(output_path, FileFormat=PP_FORMAT_PDF)
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (u'Presentation (unknown member) : PowerPoint kann ^0 auf ^1 nicht speichern.', u'Microsoft PowerPoint 2013', u'', 0, None))
```
Almost the same code works perfectly fine for Word and Excel. Has anyone an idea what I am doing wrong?

**Comment by keshrath** [comment]
This project seems to be kinda dead.

**Comment by vasily-v-ryabov** [comment]
The project is not completely dead, but maintainers are not active right now. Though I have maintenance rights, I was interested in bug fixes related only to my project that uses comtypes as a dependency.

Why are you trying `comtypes` for MS Office apps? There is perfect module `win32com.client` from `pywin32` package that works good with `IDispatch` interfaces. `comtypes` is the only normal option for custom COM interfaces. It's an overkill for `IDispatch` one.

**Comment by snoopyjc** [comment]
Try using something like this after the Open (I am using this and it works for JPG):

    powerpoint.ActivePresentation.Export(path_to_folder, "JPG")

    powerpoint.Presentations[1].Close()
    powerpoint.Quit()

Try replacing JPG with PPT.
