### ISSUE TITLE
comtypes 1.1.4 FileNotFoundError(gen_dir) on pywinauto6.4 and pyinstaller.

### ISSUE THREAD

**Issue by ferdyhong** [enthought/comtypes#145]
Hi, 
I found a problem of comtypes 1.1.4.
I installed comtypes to use pywinauto(maybe 6.3) and I used comtype(maybe 1.1.2) very well until a few days ago.
but, I think.. I probably upgraded pywinauto and comtype to latest version yesterday.
Today, I used 'pyinstaller' to make an execute file and ran the execute file. but I got the following error:

so, I downgraded comtype from 1.1.4 to 1.1.1 and than I got the results I want.

please I'll wait for your solution :)
Thank you.

(MainProcess_180123.py line 5 is "import WebPRocess"
 WebProcess line 10 is "import pywinauto.keyboard as pk")

C:\Users\hgha\PycharmProjects\closing\RPA automation\R5\bak\dist>kk.exe "C:\Users\hgha\PycharmProjects\closing\RPA automation\_180205.01\R5\R5_Xx.xlsm"
Traceback (most recent call last):
  **File "MainProcess_180123.py", line 5, in <module>**
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  **File "WebProcess.py", line 10, in <module>**
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pywinauto\__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pywinauto\findwindows.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pywinauto\controls\__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pywinauto\controls\uiawrapper.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\users\hgha\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pywinauto\uia_defines.py", line 175, in <module>
  File "site-packages\pywinauto\uia_defines.py", line 163, in _build_pattern_ids_dic
  File "site-packages\pywinauto\uia_defines.py", line 50, in __call__
  File "site-packages\pywinauto\uia_defines.py", line 60, in __init__
  File "site-packages\comtypes\client\_generate.py", line 110, in GetModule
  File "site-packages\comtypes\client\_generate.py", line 169, in _CreateWrapper
**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hgha\\AppData\\Local\\Temp\\_MEI226842\\comtypes\\gen\\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py'**
[11188] Failed to execute script MainProcess_180123

**Comment by mpunktcpunkt** [comment]
I have the same issue in 1.1.4, while 1.1.3 is working fine. I am not sure, but i think the problem has something to do with the last changes in "comtypes/comtypes/client/_code_cache.py". There is a new "gen_path" local copy of "gen.__path__". But line 70  still appends the "gen_dir" to "gen.__path__".

**Comment by vasily-v-ryabov** [comment]
Hi guys, I've started working on comtypes==1.1.5 preparation. Could you please test current master branch against your issue?

Also I'm fighting with `clear_comtypes_cache.py` usage because it has been never run for Py3 as post install step.

**Comment by vasily-v-ryabov** [comment]
@ferdyhong @mpunktcpunkt if it's still actual for you, could you please verify the fixes with `comtypes==1.1.7`?

**Comment by mpunktcpunkt** [comment]
Hi, we are using 1.1.7 now and it seems to have fixed the problem. Thank you!
