### ISSUE TITLE
comtypes fails to install on Linux

### ISSUE THREAD

**Issue by wiggin15** [enthought/comtypes#157]
I know comtypes is a Windows-only package, but we have cross-platform packages that use it on Windows and don't use it on Linux, so it is still a dependency and it gets installed on Linux systems too.
Recently, installation with "pip" is broken on Linux systems. I'm getting this (sorry for the very long output):

```
~ pip install comtypes
Collecting comtypes
  Downloading https://files.pythonhosted.org/packages/7a/fa/7c8c9c9c367d6241d520d99f31e571bdd78bc3e9034f3a4064e6ba451554/comtypes-1.1.6.zip (180kB)
    100% |████████████████████████████████| 184kB 3.2MB/s
Installing collected packages: comtypes
  Running setup.py install for comtypes ... error
    Complete output from command /root/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-GeOS89/comtypes/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-JDjKgR/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/comtypes
    copying comtypes/util.py -> build/lib/comtypes
    copying comtypes/errorinfo.py -> build/lib/comtypes
    copying comtypes/_meta.py -> build/lib/comtypes
    copying comtypes/typeinfo.py -> build/lib/comtypes
    copying comtypes/persist.py -> build/lib/comtypes
    copying comtypes/GUID.py -> build/lib/comtypes
    copying comtypes/connectionpoints.py -> build/lib/comtypes
    copying comtypes/npsupport.py -> build/lib/comtypes
    copying comtypes/logutil.py -> build/lib/comtypes
    copying comtypes/_comobject.py -> build/lib/comtypes
    copying comtypes/_safearray.py -> build/lib/comtypes
    copying comtypes/patcher.py -> build/lib/comtypes
    copying comtypes/__init__.py -> build/lib/comtypes
    copying comtypes/git.py -> build/lib/comtypes
    copying comtypes/viewobject.py -> build/lib/comtypes
    copying comtypes/safearray.py -> build/lib/comtypes
    copying comtypes/hresult.py -> build/lib/comtypes
    copying comtypes/shelllink.py -> build/lib/comtypes
    copying comtypes/messageloop.py -> build/lib/comtypes
    copying comtypes/automation.py -> build/lib/comtypes
    creating build/lib/comtypes/client
    copying comtypes/client/_code_cache.py -> build/lib/comtypes/client
    copying comtypes/client/_events.py -> build/lib/comtypes/client
    copying comtypes/client/_generate.py -> build/lib/comtypes/client
    copying comtypes/client/dynamic.py -> build/lib/comtypes/client
    copying comtypes/client/__init__.py -> build/lib/comtypes/client
    copying comtypes/client/lazybind.py -> build/lib/comtypes/client
    creating build/lib/comtypes/server
    copying comtypes/server/connectionpoints.py -> build/lib/comtypes/server
    copying comtypes/server/w_getopt.py -> build/lib/comtypes/server
    copying comtypes/server/__init__.py -> build/lib/comtypes/server
    copying comtypes/server/inprocserver.py -> build/lib/comtypes/server
    copying comtypes/server/localserver.py -> build/lib/comtypes/server
    copying comtypes/server/automation.py -> build/lib/comtypes/server
    copying comtypes/server/register.py -> build/lib/comtypes/server
    creating build/lib/comtypes/tools
    copying comtypes/tools/codegenerator.py -> build/lib/comtypes/tools
    copying comtypes/tools/typedesc_base.py -> build/lib/comtypes/tools
    copying comtypes/tools/tlbparser.py -> build/lib/comtypes/tools
    copying comtypes/tools/__init__.py -> build/lib/comtypes/tools
    copying comtypes/tools/typedesc.py -> build/lib/comtypes/tools
    creating build/lib/comtypes/test
    copying comtypes/test/test_server.py -> build/lib/comtypes/test
    copying comtypes/test/test_variant.py -> build/lib/comtypes/test
    copying comtypes/test/test_subinterface.py -> build/lib/comtypes/test
    copying comtypes/test/test_excel.py -> build/lib/comtypes/test
    copying comtypes/test/test_win32com_interop.py -> build/lib/comtypes/test
    copying comtypes/test/test_wmi.py -> build/lib/comtypes/test
    copying comtypes/test/test_GUID.py -> build/lib/comtypes/test
    copying comtypes/test/test_propputref.py -> build/lib/comtypes/test
    copying comtypes/test/test_sapi.py -> build/lib/comtypes/test
    copying comtypes/test/test_client.py -> build/lib/comtypes/test
    copying comtypes/test/test_msscript.py -> build/lib/comtypes/test
    copying comtypes/test/test_dispinterface.py -> build/lib/comtypes/test
    copying comtypes/test/test_safearray.py -> build/lib/comtypes/test
    copying comtypes/test/test_dict.py -> build/lib/comtypes/test
    copying comtypes/test/test_basic.py -> build/lib/comtypes/test
    copying comtypes/test/test_getactiveobj.py -> build/lib/comtypes/test
    copying comtypes/test/test_findgendir.py -> build/lib/comtypes/test
    copying comtypes/test/test_createwrappers.py -> build/lib/comtypes/test
    copying comtypes/test/test_casesensitivity.py -> build/lib/comtypes/test
    copying comtypes/test/TestComServer.py -> build/lib/comtypes/test
    copying comtypes/test/TestDispServer.py -> build/lib/comtypes/test
    copying comtypes/test/test_comserver.py -> build/lib/comtypes/test
    copying comtypes/test/test_ie.py -> build/lib/comtypes/test
    copying comtypes/test/test_urlhistory.py -> build/lib/comtypes/test
    copying comtypes/test/test_dyndispatch.py -> build/lib/comtypes/test
    copying comtypes/test/test_showevents.py -> build/lib/comtypes/test
    copying comtypes/test/__init__.py -> build/lib/comtypes/test
    copying comtypes/test/runtests.py -> build/lib/comtypes/test
    copying comtypes/test/test_word.py -> build/lib/comtypes/test
    copying comtypes/test/test_DISPPARAMS.py -> build/lib/comtypes/test
    copying comtypes/test/test_pump_events.py -> build/lib/comtypes/test
    copying comtypes/test/test_typeinfo.py -> build/lib/comtypes/test
    copying comtypes/test/find_memleak.py -> build/lib/comtypes/test
    copying comtypes/test/test_outparam.py -> build/lib/comtypes/test
    copying comtypes/test/test_BSTR.py -> build/lib/comtypes/test
    copying comtypes/test/test_agilent.py -> build/lib/comtypes/test
    copying comtypes/test/test_avmc.py -> build/lib/comtypes/test
    copying comtypes/test/test_QueryService.py -> build/lib/comtypes/test
    copying comtypes/test/test_collections.py -> build/lib/comtypes/test
    copying comtypes/test/setup.py -> build/lib/comtypes/test
    copying comtypes/test/TestComServer.idl -> build/lib/comtypes/test
    copying comtypes/test/TestComServer.tlb -> build/lib/comtypes/test
    copying comtypes/test/TestDispServer.idl -> build/lib/comtypes/test
    copying comtypes/test/TestDispServer.tlb -> build/lib/comtypes/test
    copying comtypes/test/mytypelib.idl -> build/lib/comtypes/test
    copying comtypes/test/mylib.idl -> build/lib/comtypes/test
    copying comtypes/test/test_jscript.js -> build/lib/comtypes/test
    running build_scripts
    creating build/scripts-2.7
    copying clear_comtypes_cache.py -> build/scripts-2.7
    changing mode of build/scripts-2.7/clear_comtypes_cache.py from 644 to 755
    running install_lib
    creating /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/util.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/errorinfo.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/_meta.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/typeinfo.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/persist.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/GUID.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/connectionpoints.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/npsupport.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/logutil.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/_comobject.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/_safearray.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/patcher.py -> /root/python/lib/python2.7/site-packages/comtypes
    creating /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_server.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_variant.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_subinterface.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_excel.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_win32com_interop.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_wmi.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_GUID.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_propputref.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_sapi.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_client.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_msscript.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_dispinterface.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_safearray.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_dict.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_basic.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_getactiveobj.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_jscript.js -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_findgendir.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_createwrappers.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestDispServer.idl -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_casesensitivity.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestComServer.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestDispServer.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_comserver.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_ie.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestComServer.idl -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_urlhistory.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/mytypelib.idl -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_dyndispatch.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_showevents.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/__init__.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/runtests.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_word.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/mylib.idl -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_DISPPARAMS.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_pump_events.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_typeinfo.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/find_memleak.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestComServer.tlb -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_outparam.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_BSTR.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/TestDispServer.tlb -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_agilent.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_avmc.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_QueryService.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/test_collections.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/test/setup.py -> /root/python/lib/python2.7/site-packages/comtypes/test
    copying build/lib/comtypes/__init__.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/git.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/viewobject.py -> /root/python/lib/python2.7/site-packages/comtypes
    creating /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/connectionpoints.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/w_getopt.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/__init__.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/inprocserver.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/localserver.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/automation.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/server/register.py -> /root/python/lib/python2.7/site-packages/comtypes/server
    copying build/lib/comtypes/safearray.py -> /root/python/lib/python2.7/site-packages/comtypes
    creating /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/_code_cache.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/_events.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/_generate.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/dynamic.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/__init__.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/client/lazybind.py -> /root/python/lib/python2.7/site-packages/comtypes/client
    copying build/lib/comtypes/hresult.py -> /root/python/lib/python2.7/site-packages/comtypes
    creating /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/tools/codegenerator.py -> /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/tools/typedesc_base.py -> /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/tools/tlbparser.py -> /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/tools/__init__.py -> /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/tools/typedesc.py -> /root/python/lib/python2.7/site-packages/comtypes/tools
    copying build/lib/comtypes/shelllink.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/messageloop.py -> /root/python/lib/python2.7/site-packages/comtypes
    copying build/lib/comtypes/automation.py -> /root/python/lib/python2.7/site-packages/comtypes
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/util.py to util.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/errorinfo.py to errorinfo.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/_meta.py to _meta.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/typeinfo.py to typeinfo.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/persist.py to persist.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/GUID.py to GUID.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/connectionpoints.py to connectionpoints.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/npsupport.py to npsupport.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/logutil.py to logutil.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/_comobject.py to _comobject.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/_safearray.py to _safearray.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/patcher.py to patcher.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_server.py to test_server.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_variant.py to test_variant.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_subinterface.py to test_subinterface.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_excel.py to test_excel.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_win32com_interop.py to test_win32com_interop.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_wmi.py to test_wmi.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_GUID.py to test_GUID.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_propputref.py to test_propputref.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_sapi.py to test_sapi.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_client.py to test_client.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_msscript.py to test_msscript.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_dispinterface.py to test_dispinterface.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_safearray.py to test_safearray.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_dict.py to test_dict.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_basic.py to test_basic.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_getactiveobj.py to test_getactiveobj.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_findgendir.py to test_findgendir.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_createwrappers.py to test_createwrappers.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_casesensitivity.py to test_casesensitivity.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/TestComServer.py to TestComServer.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/TestDispServer.py to TestDispServer.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_comserver.py to test_comserver.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_ie.py to test_ie.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_urlhistory.py to test_urlhistory.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_dyndispatch.py to test_dyndispatch.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_showevents.py to test_showevents.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/__init__.py to __init__.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/runtests.py to runtests.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_word.py to test_word.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_DISPPARAMS.py to test_DISPPARAMS.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_pump_events.py to test_pump_events.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_typeinfo.py to test_typeinfo.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/find_memleak.py to find_memleak.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_outparam.py to test_outparam.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_BSTR.py to test_BSTR.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_agilent.py to test_agilent.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_avmc.py to test_avmc.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_QueryService.py to test_QueryService.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/test_collections.py to test_collections.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/test/setup.py to setup.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/__init__.py to __init__.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/git.py to git.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/viewobject.py to viewobject.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/connectionpoints.py to connectionpoints.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/w_getopt.py to w_getopt.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/__init__.py to __init__.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/inprocserver.py to inprocserver.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/localserver.py to localserver.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/automation.py to automation.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/server/register.py to register.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/safearray.py to safearray.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/_code_cache.py to _code_cache.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/_events.py to _events.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/_generate.py to _generate.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/dynamic.py to dynamic.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/__init__.py to __init__.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/client/lazybind.py to lazybind.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/hresult.py to hresult.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/tools/codegenerator.py to codegenerator.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/tools/typedesc_base.py to typedesc_base.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/tools/tlbparser.py to tlbparser.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/tools/__init__.py to __init__.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/tools/typedesc.py to typedesc.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/shelllink.py to shelllink.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/messageloop.py to messageloop.pyc
    byte-compiling /root/python/lib/python2.7/site-packages/comtypes/automation.py to automation.pyc
    running install_scripts
    running egg_info
    writing comtypes.egg-info/PKG-INFO
    writing top-level names to comtypes.egg-info/top_level.txt
    writing dependency_links to comtypes.egg-info/dependency_links.txt
    reading manifest file 'comtypes.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'comtypes.egg-info/SOURCES.txt'
    copying build/scripts-2.7/clear_comtypes_cache.py -> /root/python/bin
    changing mode of /root/python/bin/clear_comtypes_cache.py to 755
    running install_egg_info
    Copying comtypes.egg-info to /root/python/lib/python2.7/site-packages/comtypes-1.1.6-py2.7.egg-info
    writing list of installed files to '/tmp/pip-record-JDjKgR/install-record.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GeOS89/comtypes/setup.py", line 175, in <module>
        dist = setup(**setup_params)
      File "/root/python/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/root/python/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/root/python/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/root/python/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-GeOS89/comtypes/setup.py", line 121, in run
        raise RuntimeError("Can't find '%s'" % (filename,))
    RuntimeError: Can't find '/root/python/Scripts/clear_comtypes_cache.py'
```
I sometimes have to pass `--no-cache-dir` to reproduce this reliably.
It seems like we're trying to execute `Scripts/clear_comtypes_cache.py`, but `Scripts` is a directory that exists only on Windows.

pip version: 10.0.1
Python version: 2.7.8
Operating system: I'm getting this on a variety of Linux distributions and versions, e.g. Ubuntu 16.04
comtypes version: 1.1.6

**Comment by easybe** [comment]
Looks similar on Windows:

```    
PS C:\> pip.exe install comtypes==1.1.6 --no-cache-dir --target="C:\tmp"
(...)
    byte-compiling c:\users\me\appdata\local\temp\pip-target-jywhcd\lib\python\comtypes\__init__.py to __init__.pyc
    running install_scripts
    running egg_info
    writing comtypes.egg-info\PKG-INFO
    writing top-level names to comtypes.egg-info\top_level.txt
    writing dependency_links to comtypes.egg-info\dependency_links.txt
    reading manifest file 'comtypes.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'comtypes.egg-info\SOURCES.txt'
    creating c:\users\me\appdata\local\temp\pip-target-jywhcd\bin
    copying build\scripts-2.7\clear_comtypes_cache.py -> c:\users\me\appdata\local\temp\pip-target-jywhcd\bin
    running install_egg_info
    Copying comtypes.egg-info to c:\users\me\appdata\local\temp\pip-target-jywhcd\lib\python\comtypes-1.1.6-py2.7.egg-info
    writing list of installed files to 'c:\users\me\appdata\local\temp\pip-record-sf1aza\install-record.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\me\appdata\local\temp\pip-install-_ssmvn\comtypes\setup.py", line 175, in <module>
        dist = setup(**setup_params)
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\me\appdata\local\temp\pip-install-_ssmvn\comtypes\setup.py", line 119, in run
        filename = os.path.join(self.prefix, "Scripts", "clear_comtypes_cache.py")
      File "c:\python27\lib\ntpath.py", line 65, in join
        result_drive, result_path = splitdrive(path)
      File "c:\python27\lib\ntpath.py", line 115, in splitdrive
        if len(p) > 1:
    TypeError: object of type 'NoneType' has no len()
```

Same for 1.1.5, 1.1.4 works.

**Comment by vasily-v-ryabov** [comment]
Hi @easybe the issue has been fixed in `comtypes==1.1.7` on Windows (see #158). Can you confirm the fix is good for Linux also?

**Comment by easybe** [comment]
Fixed, successfully ran:
```
pip install comtypes==1.1.7 --no-cache-dir --target="/tmp"
```

**Comment by wiggin15** [comment]
Fixed in #158

**Comment by KavishGoyal** [comment]
Not working in ubuntu 20.04.

**Comment by KavishGoyal** [comment]
Anyone suggest any way how to resolve this issue on ubuntu 20.04.

**Comment by vasily-v-ryabov** [comment]
Latest pip3 can install comtypes==1.1.7 just fine (both python2 and python3). I've just checked it on Ubuntu 20.04 on WSL1. @KavishGoyal can you provide more detailed bug report?

pip2 version: 20.3.3
pip3 version: 20.0.2

**Comment by KavishGoyal** [comment]
Thanks, Vasily for your help, really appreciate it. And it has resolved.

**Comment by FIRDOUS-BHAT** [comment]
What's the similar package for linux?

**Comment by stMerlHin** [comment]
> Hi @SIRISHA-SHARON comtypes is Windows only package.

Is a linux port planed  ?

**Comment by junkmd** [comment]
Hi, @stMerlHin 

To port this project to non-Windows platforms, COM itself needs to become usable outside of Windows.

I have previously explained to the community that COM is specific to Windows.
Please see https://github.com/enthought/comtypes/issues/479#issuecomment-1550658623.

For the software you wish to operate, it may be faster to look for an API other than COM, rather than waiting for Microsoft to make COM available on other platforms.

**Comment by stMerlHin** [comment]
thanks for the fast reply.
