### ISSUE TITLE
Installing version 1.1.6 to custom location fails on Windows

### ISSUE THREAD

**Issue by easybe** [enthought/comtypes#158]
Same for 1.1.5, 1.1.4 works.

```    
PS C:\> pip.exe install comtypes==1.1.6 --no-cache-dir --target="C:\tmp"
(...)
    byte-compiling c:\users\me\appdata\local\temp\pip-target-jywhcd\lib\python\comtypes\__init__.py to __init__.pyc
    running install_scripts
    running egg_info
    writing comtypes.egg-info\PKG-INFO
    writing top-level names to comtypes.egg-info\top_level.txt
    writing dependency_links to comtypes.egg-info\dependency_links.txt
    reading manifest file 'comtypes.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'comtypes.egg-info\SOURCES.txt'
    creating c:\users\me\appdata\local\temp\pip-target-jywhcd\bin
    copying build\scripts-2.7\clear_comtypes_cache.py -> c:\users\me\appdata\local\temp\pip-target-jywhcd\bin
    running install_egg_info
    Copying comtypes.egg-info to c:\users\me\appdata\local\temp\pip-target-jywhcd\lib\python\comtypes-1.1.6-py2.7.egg-info
    writing list of installed files to 'c:\users\me\appdata\local\temp\pip-record-sf1aza\install-record.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\me\appdata\local\temp\pip-install-_ssmvn\comtypes\setup.py", line 175, in <module>
        dist = setup(**setup_params)
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\me\appdata\local\temp\pip-install-_ssmvn\comtypes\setup.py", line 119, in run
        filename = os.path.join(self.prefix, "Scripts", "clear_comtypes_cache.py")
      File "c:\python27\lib\ntpath.py", line 65, in join
        result_drive, result_path = splitdrive(path)
      File "c:\python27\lib\ntpath.py", line 115, in splitdrive
        if len(p) > 1:
    TypeError: object of type 'NoneType' has no len()
```

**Comment by easybe** [comment]
Duplicate of #157?

**Comment by vasily-v-ryabov** [comment]
Hi @easybe sorry for late response and thanks for the report! I've found the root cause and fixed it. Regression test is also written. Will post comtypes-1.1.7 soon.

**Comment by wiggin15** [comment]
Looks like this fixed the installation on Linux too. Thanks.

**Comment by yurgenzzz** [comment]
I downloaded comtypes in zip file and used `pip install comtypes-1.1.7.zip` to install it. Successfully installed, but when I try to import the module, it shows error message:
`>>> import comtypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python367\lib\comtypes\__init__.py", line 381
    except COMError, err:
                   ^
SyntaxError: invalid syntax`
