### ISSUE TITLE
comtypes.shelllink example fails on python 3.6.0 64bit

### ISSUE THREAD

**Issue by itziakos** [enthought/comtypes#162]
```
> python -m comtypes.shelllink
Traceback (most recent call last):
  File "c:\...\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\...\lib\site-packages\comtypes\shelllink.py", line 216, in <module>
    pf.Save("foo.lnk", True)
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
<POINTER(IShellLinkW) ptr=0x265b16257d0 at 265b4002cc8>
C:\...\python.exe
('c:\\...\\python.exe', 1)
```

The same code passes on python 2.7 64bit

**Comment by itziakos** [comment]
The error is coming from the Save method of IPersistFile which expects two arguments

```python
        COMMETHOD(
            [], HRESULT, 'Save',
            (['in'], LPCOLESTR, 'pszFileName'),
            (['in'], BOOL, 'fRemember')),
```

**Comment by itziakos** [comment]
>  the example you gave is working on my Windows 7 VM:

I am running Windows 10. I think it did not matter let me check.

**Comment by andrewcollette** [comment]
It does indeed fail on my Win10 VM, with the error you posted. :/

**Comment by itziakos** [comment]
> It does indeed fail on my Win10 VM, with the error you posted. :/

That sounds fun

**Comment by andrewcollette** [comment]
So what you're saying is.... the parameter *was* incorrect. 😄

**Comment by junkmd** [comment]
Since I thought that the problem had been resolved, I closed the issue.
