### ISSUE TITLE
test_SAFEARRAY does not work on array of VARIANTs

### ISSUE THREAD

**Issue by Antonm5012** [enthought/comtypes#163]
======================================================================
ERROR: test_VT_VARIANT_ndarray (__main__.SafeArrayTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\comtypes\test\test_safearray.py", line 236, in test_VT_VARIANT_ndarray
    sa = t.from_param(inarr)
  File "C:\Anaconda3\lib\site-packages\comtypes\safearray.py", line 206, in from_param
    value = cls.create(value, extra)
  File "C:\Anaconda3\lib\site-packages\comtypes\safearray.py", line 115, in create
    return cls.create_from_ndarray(value, extra)
  File "C:\Anaconda3\lib\site-packages\comtypes\safearray.py", line 158, in create_from_ndarray
    value = _ndarray_to_variant_array(value)
  File "C:\Anaconda3\lib\site-packages\comtypes\safearray.py", line 380, in _ndarray_to_variant_array
    varr.flat = [VARIANT(v) for v in value.flat]
**ValueError: setting an array element with a sequence.**

Is there something that I am missing? 
I am using Python 3.6.5

I will appreciate any advice!

Many thanks

**Comment by Antonm5012** [comment]
The test passes if numpy is downgraded to 1.11.3
