### ISSUE TITLE
Syntax error when trying to import comtypes on Python 3.6.7

### ISSUE THREAD

**Issue by yurgenzzz** [enthought/comtypes#180]
Sorry, I'm a totally new in Python, Git and such, so maybe that problem was solved before, and I just missed it... I need to install comtypes locally with pip. The PC is offline, Win 7 x86.
I downloaded comtypes in zip file and used `pip install comtypes-1.1.7.zip` to install it. Successfully installed, but when I try to import the module, it shows error message:
>>> import comtypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python367\lib\comtypes\__init__.py", line 381
except COMError, err:
               ^
SyntaxError: invalid syntax

**Comment by diogofriggo** [comment]
I'm experiencing the same error on Python 3.7.10 and comtypes 1.1.10

**Comment by drijonha** [comment]
I'm experiencing the same error on Python 3.9.0 and comtypes 1.1.10

**Comment by Vivojay** [comment]
I'm experiencing the same error on Python 3.9.9 and comtypes 1.1.10

**Comment by filipporomani** [comment]
Same for me

**Comment by lededev** [comment]
`except COMError, err:`
change to
`except (COMError, err) as err:`

**Comment by Vivojay** [comment]
So do we have to fork it and then download that forked git repo instead of comtypes?

**Comment by lededev** [comment]
or you can use Python 3.9.

**Comment by Vivojay** [comment]
I am using python 3.9.9 ...

**Comment by lededev** [comment]
Anaconda's python 3.9.7 work well with comtypes.

**Comment by DH-MP** [comment]
On python 3.7, workaround for me is downgrading to wheel==0.36.2 and setuptools==57.0.0
pip install setuptools==57.0.0
pip install wheel==0.36.2
then pip uninstall comtypes 
and pip install --no-cache-dir comtypes  (make sure it's not using cache)


If you are doing it in a requirement file do the setuptools and wheel seperately (another requirement file) before installing the main requirement file.
pip install --no-cache-dir -r download_setup.txt
pip install --no-cache-dir -r your_requirement.txt

**Comment by PhilippSelenium** [comment]
Come on, two years and still not fix ...

**Comment by Vivojay** [comment]
I was wondering the same thing...
I would really wish they made this fix...

**Comment by filipporomani** [comment]
> On python 3.7, workaround for me is downgrading to wheel==0.36.2 and setuptools==57.0.0 pip install setuptools==57.0.0 pip install wheel==0.36.2 then pip uninstall comtypes and pip install --no-cache-dir comtypes (make sure it's not using cache)
> 
> If you are doing it in a requirement file do the setuptools and wheel seperately (another requirement file) before installing the main requirement file. pip install --no-cache-dir -r downgrade.txt pip install --no-cache-dir -r your_requirement.txt

Thanks! It worked fine for me!

**Comment by filipporomani** [comment]
Couldn't this be a fix?

**Comment by cfarrow** [comment]
Hi all. For the last few years @vasily-v-ryabov has been contributing time to the project as he can. I worked on it prior to that. In both cases, we put in time as needed to support work and hobby projects. I arranged for Enthought hosting so the project would have testing automation, but Enthought is otherwise not associated with comtypes. 

I'm happy to bring on other contributors to the project to help keep it running for those who need it. Please let me know if you have the time and willingness to review and test PRs and to put out new releases. Thank you.

**Comment by cmin764** [comment]
We at Robocorp are having the same [issue](https://github.com/robocorp/rpaframework/issues/359) in production and it's a blocker, one that pushes us to fork our own version of **comtypes** in order to place a proper fix, otherwise we keep breaking people's virtual environments given the latest **setuptools** update.

Can you provide an ETA for such Py3 compatibility fix?

**Comment by PhilippSelenium** [comment]
> We at Robocorp are having the same [issue](https://github.com/robocorp/rpaframework/issues/359) in production and it's a blocker, one that pushes us to fork our own version of **comtypes** in order to place a proper fix, otherwise we keep breaking people's virtual environments given the latest **setuptools** update.
> 
> Can you provide an ETA for such Py3 compatibility fix?

@cmin764  Why don't you at robocorp provide such a fix to the community instead of forking your own version?

**Comment by cmin764** [comment]
> > We at Robocorp are having the same [issue](https://github.com/robocorp/rpaframework/issues/359) in production and it's a blocker, one that pushes us to fork our own version of **comtypes** in order to place a proper fix, otherwise we keep breaking people's virtual environments given the latest **setuptools** update.
> > Can you provide an ETA for such Py3 compatibility fix?
> 
> @cmin764 Why don't you at robocorp provide such a fix to the community instead of forking your own version?

We'll do it at the same time for sure and we can't wait until the official package gets fixed, that's why both.

**Comment by PhilippSelenium** [comment]
@cmin764 I do not understand your answer: If you are providing a fix via a PR to this repository why do you need an ETA for the fix?

**Comment by kdschlosser** [comment]
I submitted a PR with the code converted to python 3 syntax.  The problem is the setup program in comtypes is using build_py_2to3 in distutils and build_py_2to3 was dropped starting with python 3.9. So the code never gets converted.

I see no reason why Python 2 should be supported anymore anyhow.

**Comment by cmin764** [comment]
Here's also a minimally intrusive PR adopting the behaviour back: https://github.com/enthought/comtypes/pull/254
Although I'm agreeing with @kdschlosser incentive of defaulting to Python 3 first and supporting the syntax straight from the code.

**Comment by kdschlosser** [comment]
I also found an issue with BSTR and \_type\_ not being set correctly. I am testing it right now to see if I have solved the problem. A BSTR is the same thing as a pointer to WCHAR and I am not sure as to why \_SimpleCData was subclassed instead of c\_wchar\_p. the type for w\_char\_p is `"Z"` where as  comtypes has the  type set for BSTR as `"X"`.

I am not sure if that is what is causing my problem yet but on x86 I get a COM error telling me that the data type is too small by 4 bytes and BSTR is the data type for the only parameter the function takes.

I am still messing with it to see if that is what the problem is.

**Comment by kdschlosser** [comment]
Welp BSTR wasn't causing that problem but it may have been causing a heap corruption issue I was having that seems to have gone away now. I do not know what the different \_type\_  specifiers are or what they mean. Never got into the core code of python too much.

**Comment by cmin764** [comment]
Thank you @kdschlosser , your PR got merged and we'll get a [release](https://github.com/enthought/comtypes/pull/253#issuecomment-1024295338) next week as well!

**Comment by Vivojay** [comment]
> On python 3.7, workaround for me is downgrading to wheel==0.36.2 and setuptools==57.0.0 pip install setuptools==57.0.0 pip install wheel==0.36.2 then pip uninstall comtypes and pip install --no-cache-dir comtypes (make sure it's not using cache)
> 
> If you are doing it in a requirement file do the setuptools and wheel seperately (another requirement file) before installing the main requirement file. pip install --no-cache-dir -r downgrade.txt pip install --no-cache-dir -r your_requirement.txt

Great! It worked for me...

**Comment by patelakash317** [comment]
For someone if it is still not working and if not needed uninstall comtypes, that works for me now. Finally.

**Comment by cmin764** [comment]
> For someone if it is still not working and if not needed uninstall comtypes, that works for me now. Finally.

I think that's not a fix if there's code importing it right? I'm curious, how it ended up in producing Syntax Errors in the first place if the code can run without this package?

**Comment by yotamsVIM** [comment]
> 1.1.11 is out. Please check.

This solved the issue for me under python 3.8.10 (32bit)

**Comment by DH-MP** [comment]
> On python 3.7, workaround for me is downgrading to wheel==0.36.2 and setuptools==57.0.0 pip install setuptools==57.0.0 pip install wheel==0.36.2 then pip uninstall comtypes and pip install --no-cache-dir comtypes (make sure it's not using cache)
> 
> If you are doing it in a requirement file do the setuptools and wheel seperately (another requirement file) before installing the main requirement file. pip install --no-cache-dir -r downgrade.txt pip install --no-cache-dir -r your_requirement.txt

Tested and working with setup v62 with comtype v1.1.11

**Comment by cmin764** [comment]
> Hello everyone, I've found the syntax issues using comtypes on python 3.9.12... I was wondering if anyone can help me. Thanks

Are you using the latest `comtypes==1.1.11`? If yes, can you post your traceback here so we have more details about the issue?

**Comment by Elisa-code184** [comment]
I solved using an older version of python (3.7) and anaconda (5.3.0)...
I was using the anaconda last version available and comtypes == 1.1.4, but I had issues (syntax errors) with some modules in comtypes: the syntax was not updated (I think from python 2).

**Comment by junkmd** [comment]
@Elisa-code184

> pip install setuptools==57.0.0
> pip install wheel==0.36.2
> then pip uninstall comtypes
https://github.com/enthought/comtypes/issues/180#issuecomment-1009586423

This may solve the `SyntaxError`.
