### ISSUE TITLE
Powerpoint Office 365: ModuleNotFoundError: No module named 'comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0'

### ISSUE THREAD

**Issue by snoopyjc** [enthought/comtypes#183]
A new version of Powerpoint got pushed to my machine (Office 365) and that's the end of using it with comtypes:

```
Traceback (most recent call last):
  File "ppt.py", line 48, in <module>
    export_presentation('Presentation1.pptx', '.')
  File "ppt.py", line 34, in export_presentation
    powerpoint = comtypes.client.CreateObject("Powerpoint.Application")
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\_generate.py", line 172, in _CreateWrapper
    generate_module(tlib, ofi, pathname)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\tlbparser.py", line 750, in generate_module
    gen.generate_code(list(items.values()), filename=pathname)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 241, in generate_code
    self.generate_all(items)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 189, in generate_all
    self.generate(item)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 701, in ComInterface
    self.generate(itf.get_head())
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 722, in ComInterfaceHead
    self.generate(base.get_head())
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\tools\codegenerator.py", line 629, in External
    comtypes.client.GetModule(ext.tlib)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "H:\software\Powerpoint\venv\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
ModuleNotFoundError: No module named 'comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0'
```

**Comment by snoopyjc** [comment]
I fixed this by installing this change: "Fix importing newly-created modules on Python 3 #172"
