### ISSUE TITLE
ValueError: NULL COM pointer access

### ISSUE THREAD

**Issue by snoopyjc** [enthought/comtypes#185]
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import comtypes.client
>>> w = comtypes.client.CreateObject("Word.Application")
>>> w.Visible = True
>>> d = w.Documents.Open('H:\software\AAO\t.doc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "H:\software\AAO\venv\lib\site-packages\comtypes\_meta.py", line 13, in _wrap_coclass
    result = punk.QueryInterface(itf)
  File "H:\software\AAO\venv\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
**ValueError: NULL COM pointer access**

**Comment by junkmd** [comment]
@snoopyjc

To break down the cause of this, I would need to see how other COM objects and office APIs behave in your environment.

Due to no recent activity, I will close this issue.
If the issue remains, please re-open.

**Comment by vasily-v-ryabov** [comment]
@snoopyjc 
This is most probably wrong path to the document:
```
d = w.Documents.Open('H:\software\AAO\t.doc')
```
The correct path should use raw string to prevent escape sequence propagation like `\t` which is tab.
So the NULL pointer error comes from the application.
Correct code:
```
d = w.Documents.Open(r'H:\software\AAO\t.doc')
# or
d = w.Documents.Open('H:\\software\\AAO\\t.doc')
```
