### ISSUE TITLE
comtypes.client.GetModule("UIAutomationCore.dll") failed in python 3.7.6

### ISSUE THREAD

**Issue by yinkaisheng** [enthought/comtypes#202]
It worked in 3.7.3, but failed in 3.7.6.

Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import comtypes
import comtypes.client
comtypes.client.GetModule("UIAutomationCore.dll")

Traceback (most recent call last):
  File "D:\Python37\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python37\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "D:\Python37\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "D:\Python37\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "D:\Python37\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1244, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "D:\Python37\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "D:\Python37\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "D:\Python37\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
>>>

**Comment by vasily-v-ryabov** [comment]
This is wrong fix in Python 3.7.6 and 3.8.1. This is already reverted in Python (3.8.2rc1 is in validation now, so there is a hope to release Python 3.8.2 where it should work). Now just install earlier Python version.

The core of the problem is a missing feature in libffi (this is calling convention handling library used by ctypes for Python/C integration). But this feature is unlikely to be implemented soon.

**Comment by yinkaisheng** [comment]
Thanks.

**Comment by Wang-zhipeng** [comment]
I also have the problem:
when I execute .py, everything works well, but I use pyinstaller(3.6) build to exe, and run exe on another system that has no python environment, error occured. my python version 3.7.2
Traceback (most recent call last):
  File "run.py", line 73, in main
  File "Test_Suite\multiple_display_wes.py", line 99, in start
  File "Common\vdi_connection.py", line 79, in wrapper
  File "Common\vdi_connection.py", line 657, in logon
  File "Common\vdi_connection.py", line 641, in close_citrix
  File "site-packages\uiautomation\uiautomation.py", line 5860, in Exists
  File "site-packages\uiautomation\uiautomation.py", line 7683, in FindControl
  File "site-packages\uiautomation\uiautomation.py", line 7465, in GetRootControl
  File "site-packages\uiautomation\uiautomation.py", line 51, in instance
  File "site-packages\uiautomation\uiautomation.py", line 56, in __init__
  File "site-packages\comtypes\client\_generate.py", line 110, in GetModule
  File "site-packages\comtypes\client\_generate.py", line 172, in _CreateWrapper
  File "site-packages\comtypes\tools\tlbparser.py", line 750, in generate_module
  File "site-packages\comtypes\tools\codegenerator.py", line 241, in generate_code
  File "site-packages\comtypes\tools\codegenerator.py", line 189, in generate_all
  File "site-packages\comtypes\tools\codegenerator.py", line 185, in generate
  File "site-packages\comtypes\tools\codegenerator.py", line 701, in ComInterface
  File "site-packages\comtypes\tools\codegenerator.py", line 185, in generate
  File "site-packages\comtypes\tools\codegenerator.py", line 722, in ComInterfaceHead
  File "site-packages\comtypes\tools\codegenerator.py", line 185, in generate
  File "site-packages\comtypes\tools\codegenerator.py", line 722, in ComInterfaceHead
  File "site-packages\comtypes\tools\codegenerator.py", line 185, in generate
  File "site-packages\comtypes\tools\codegenerator.py", line 629, in External
  File "site-packages\comtypes\client\_generate.py", line 110, in GetModule
  File "site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
  File "site-packages\comtypes\client\_generate.py", line 24, in _my_import
ModuleNotFoundError: No module named 'comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0'

**Comment by vasily-v-ryabov** [comment]
Hi @Wang-zhipeng this is completely different problem. First you need to know that `comtypes` generates Python code for UIAutomationCore.dll on the fly and saves it to cached .py file which is missing in your case (`_00020430_0000_0000_C000_000000000046_0_2_0.py`). The file name contains GUID of the COM library. You need some trick with PyInstaller to include this cached file into your executable.

**Comment by yixue99** [comment]
I use pyinstaller build to exe, and run exe on another system that has no python environment, it can't run. my python version 3.9.4,UIAutomation version  2.0.15

**Comment by junkmd** [comment]
Note:
reported in https://github.com/python/cpython/pull/16799, resolved (reverted) in https://github.com/python/cpython/pull/17960, 
and fixed in Python 3.7.7 and 3.8.2.

From https://github.com/python/cpython/pull/16799#issuecomment-612353119
> The reverting change was committed on Jan 12, 2020. Python versions 3.7.7 (released Mar 10, 2020) and 3.8.2 (released Feb 24, 2020) should have the reversion.
