### ISSUE TITLE
SyntaxError: invalid syntax when installing with setuptools >= 60.0.0

### ISSUE THREAD

**Issue by KORraNpl** [enthought/comtypes#244]
Win10 64bit
Python 3.9.9 64bit
setuptools >= 60.0.0

**Steps**
1. Install comtypes via `pip install comtypes`
2. Launch `python` and execute `import comtypes`

**Expected**
* `comtypes` imported

**Actual**
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\KORraN\Desktop\da_tests\venv\lib\site-packages\comtypes\__init__.py", line 375
    except COMError, err:
                   ^
SyntaxError: invalid syntax
```

**Additional notes**
[setup.py](https://github.com/enthought/comtypes/blob/master/setup.py):
```python
try:
    from distutils.command.build_py import build_py_2to3 as build_py
except ImportError:
    from distutils.command.build_py import build_py
```

Importing `build_py_2to3` fails and I believe that results in code not being translated to Python 3.

It works fine with setuptools 59.8.0, although already in version [58.0.0](https://setuptools.pypa.io/en/latest/history.html#v58-0-0) I found information (although I'm not sure if it's 100% related):

> #2086: Removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using PEP 518 build-requires.

**Comment by KORraNpl** [comment]
After a bit of looking around, here's what I've found:
* support for 2to3 was indeed dropped in setuptools 58.0.0
* but until version 60.0 it was using distutils from Python installation (which contains `build_py_2to3` in 3.9.9 and 3.10.1), now it uses its own copy of the library without this class - https://setuptools.pypa.io/en/latest/history.html#v60-0-0
* **as mentioned in the change log, setting `SETUPTOOLS_USE_DISTUTILS=stdlib` helps work around the issue**.

**Comment by mworion** [comment]
Run into same issue using pywinauto.

**Comment by PhilippSelenium** [comment]
Running into the same problem with python 3.8 ... this is a real blocker.

**Comment by Darkstepan** [comment]
I have the same issue while using pywinauto.

**Comment by YoungMan3281** [comment]
hmmm...Wondered if there will be a verion support python3 by installed with pip.

**Comment by DH-MP** [comment]
Workaround is downgrading to setuptool==57.0.0 the pip uninstall comtypes and pip install --no-cache-dir comtype

**Comment by kdschlosser** [comment]
https://github.com/enthought/comtypes/releases/tag/1.1.11

**Comment by KORraNpl** [comment]
I can confirm that importing 1.1.11 works fine with setuptools 60.9.0, so I'm closing this ticket. Thanks!
