### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CUIAutomation'

### ISSUE THREAD

**Issue by haohetao** [enthought/comtypes#286]
> Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from pywinauto.application import Application
  File "C:\Python27\lib\site-packages\pywinauto\__init__.py", line 89, in <modul
e>
    from . import findwindows
  File "C:\Python27\lib\site-packages\pywinauto\findwindows.py", line 42, in <mo
dule>
    from . import controls
  File "C:\Python27\lib\site-packages\pywinauto\controls\__init__.py", line 36,
in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper
 module)
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47
, in <module>
    from ..uia_defines import IUIA
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 181, in <m
odule>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 169, in _b
uild_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 50, in __c
all__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 63, in __i
nit__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: 'module' object has no attribute 'CUIAutomation'

comtypes 1.1.11
python 2.7.18
windows xp sp3

**Comment by vasily-v-ryabov** [comment]
Try to clean up comtypes cache by the script in `C:\Python27\Scripts\`

**Comment by junkmd** [comment]
This issue has been without updates for a long time, and support for Python 2.7 has been dropped.
The situation can be resolved by running `py -m comtypes.clear_cache`.
See also #517 and #114.

I will close this issue.
