### ISSUE TITLE
comtypes.client.CreateObject fails in pyinstaller executable

### ISSUE THREAD

**Issue by Andrea-Oliveri** [enthought/comtypes#340]
Good Morning,
thank you for this very useful package.
I am trying to use comtypes to automate an export task in Powerpoint.
My script works flawlessly when running
`python render_pptx_as_png.py` 
from the command line, with the following anaconda environment activated:
```
# Name                    Version                   Build  Channel
altgraph                  0.17.2                   pypi_0    pypi
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15        py39haa95532_0
comtypes                  1.1.13                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0
pefile                    2022.5.30                pypi_0    pypi
pip                       22.1.2           py39haa95532_0
pyinstaller               5.1                      pypi_0    pypi
pyinstaller-hooks-contrib 2022.7                   pypi_0    pypi
python                    3.9.12               h6244533_0
pywin32-ctypes            0.2.0                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                61.2.0           py39haa95532_0
sqlite                    3.39.2               h2bbff1b_0
tzdata                    2022a                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
```

However, it fails with the following error when running the executable of this same program generated by pyinstaller:
```
Traceback (most recent call last):
  File "render_pptx_as_png.py", line 191, in convert
  File "comtypes\client\__init__.py", line 250, in CreateObject
  File "comtypes\client\__init__.py", line 188, in _manage
  File "comtypes\client\__init__.py", line 112, in GetBestInterface
AttributeError: module 'comtypes.gen.PowerPoint' has no attribute '_Application'
```

The failure occurrs on this line:
`powerpoint = client.CreateObject('Powerpoint.Application')`

and this is the pyinstaller .spec file which I use to make the executable:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['render_pptx_as_png.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Render PPTX as PNG',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico'
)
```

I have tried substituting the call to `comtypes.client.CreateObject` with `comtypes.client.GetActiveObject` but it fails with the same error. 
May I please ask for your help to solve this issue?
Thank you in advance.

**Comment by junkmd** [comment]
@Andrea-Oliveri 

Do you remember the version of each package when it was executable with `pyinstaller`?

Or is this the first time you have tried to use `pyinstaller`?

**Comment by junkmd** [comment]
@Andrea-Oliveri 

and see https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/342

the issue treats problem with `pywinauto` and `comtypes`.  
`pywinauto` is also using `comtypes`.
It may help you.

**Comment by junkmd** [comment]
[This](https://github.com/enthought/comtypes/issues/340#issuecomment-1220820964) is a concise summary of what should be done when using pyinstaller.
We should include troubleshooting contents like this in the wiki or store the documentation in the repository.
