### ISSUE TITLE
`npsupport` does not work with `numpy>=2.0.0`

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#573]
I noticed that the tests for `comtypes.npsupport` fail when `numpy==2.0.0` is installed.

```
ERROR: test_VT_I4_ndarray_enabled (test_npsupport.NumpySupportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\comtypes\comtypes\test\test_npsupport.py", line 66, in call_enabled
    func(self)
  File "...\comtypes\comtypes\test\test_npsupport.py", line 188, in test_VT_I4_ndarray
    sa = t.from_param(in_arr)
  File "...\comtypes\comtypes\safearray.py", line 214, in from_param
    value = cls.create(value, extra)
  File "...\comtypes\comtypes\safearray.py", line 122, in create
    return cls.create_from_ndarray(value, extra)
  File "...\comtypes\comtypes\safearray.py", line 171, in create_from_ndarray
    raise TypeError("Wrong array item type")
TypeError: Wrong array item type
```

To avoid a situation where we can't develop other features until `npsupport` supports `numpy==2.0.0`, I will change the GHA workflow so that the `numpy` installed in the CI environment is a version lower than `2.0.0` for the time being.

I'm not particularly familiar with the use cases for `npsupport`, so I hope that community members who have a high priority for `npsupport` will fix it.

**Comment by junkmd** [comment]
> Previously, `comtypes` relied on private `numpy.ctypeslib` APIs and patched or overwrote NumPy's internal implementations. Instead, we can modify `_npsupport.py` to construct its own mapping between `ctypes` types and NumPy `dtypes`.
> 
> Additionally, we can address the size mismatch with `SAFEARRAY`. This issue arose when NumPy 2.x defaulted to `int64` for unspecified types. To resolve it, we can introduce `numpy.can_cast` and `value.astype(expected_dtype)` into the `create_from_ndarray`. Consequently, the `test_VT_I4_ndarray` test case has been adjusted to explicitly specify `dtype=numpy.int32` when creating `numpy.array` instances.

Regarding the comment above, I realized that `test_npsupport` passes even with `numpy>=2.0.0` simply by explicitly specifying the `dtype`, without needing to change the production code.

Therefore, I'll resubmit the PR and save the update to the old `npsupport` production code for another time.
