### ISSUE TITLE
64-bit comtypes raise "Bad variable type."

### ISSUE THREAD

**Issue by shgohh** [enthought/comtypes#66]
The following code work fine in 32-bit comtypes:-

    C:\Users\vm>python
    Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from comtypes.client import CreateObject
    >>>
    >>> ie = CreateObject("InternetExplorer.Application")
    >>> ie.Visible = True
    >>> ie.Navigate('www.google.com')
    0
    >>> ie.document.getElementsByName('q')[0].value = 'pypi comtypes'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\comtypes-1.1.0-py2.7.egg\comtypes\__init__.py", line 380, in __getitem__
        result = self.Item(*args)
    _ctypes.COMError: (-2147352568, 'Bad variable type.', (None, None, None, 0, None))
    >>>

**Comment by shgohh** [comment]
I've re-test with latest release 1.1.2, which fixed the issue, my test environment as follow:-

OS: Windows 7 Professional Service Pack 1
Python: 2.7.11 64-bit
IE: 9.0.8112.16421 64-bit Edition

I also tested with another environment:-

OS: Windows 10 Enterprise
Python: 3.5.1 64-bit
IE: 11.20.10586.0 64-bit Edition

However, I'm getting the same issue reported #92, but commented out the two lines allow me to continue the test, it works.

Thanks for getting this fixed.
