### ISSUE TITLE
comtypes 1.1.0 and 1.1.1 does not work under pypy 2.51

### ISSUE THREAD

**Issue by rjungbeck** [enthought/comtypes#77]
```
>>>> import comtypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\pypy\site-packages\comtypes\__init__.py", line 1171, in <module>
    class IPersist(IUnknown):
  File "C:\pypy\site-packages\comtypes\__init__.py", line 1176, in IPersist
    ( ['out'], POINTER(GUID), 'pClassID' )),
  File "C:\pypy\site-packages\comtypes\__init__.py", line 1093, in COMMETHOD
    from comtypes.automation import VARIANT
  File "C:\pypy\site-packages\comtypes\automation.py", line 538, in <module>
    VARIANT.null = VARIANT(None)
  File "C:\pypy\site-packages\comtypes\automation.py", line 187, in __init__
    self.value = args[0]
  File "C:\pypy\site-packages\comtypes\automation.py", line 220, in _set_value
    self.vt = VT_NULL
  File "C:\pypy\lib_pypy\_ctypes\structure.py", line 122, in __set__
    obj._buffer.__setattr__(self.name, arg)
AttributeError: C Structure has no attribute vt
```

comtypes 1.0.0 does work

**Comment by cfarrow** [comment]
Thanks for the bug report. Support for decimal types was added in 1.0.0 and this required a change in the `VARIANT` structure. I have a feeling this is what is causing the problem.

Prior to the change, `VARIANT` was a structure containing a union. Now it is a structure containing a union, which itself contains a structure with a union. This change brings the comtypes `VARIANT` definition closer to the [C++ definition](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221627%28v=vs.85%29.aspx).

I suspect this is probably an issue with pypy's ctypes implementation. A quick google search indicates that the pypy implementation initializes fields differently than the CPython one (see [here](https://gist.github.com/marianoguerra/3281751)).

It's worth raising a bug report on pypy about this. I'll see if I can do something on this end, but any help you or the community can give with this would help speed this along.

**Comment by junkmd** [comment]
Python 2.5 is no longer supported from comtypes==1.0.0.

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/CHANGES.txt#L141-L149

@rjungbeck
If you run the current `comtypes` on pypy and have problems, please submit another issue.
