### ISSUE TITLE
Many failures in test_createwrappers under 64-bit python

### ISSUE THREAD

**Issue by cfarrow** [enthought/comtypes#9]
This was acquired on Windows 7. The test attempts to create wrappers for everything it can find, which differs from system to system. (On 32-bit windows XP only about 1300 files are wrapped.)

An investigation of one of the failures indicated that unions may not be built or validated properly in all cases.

``` python

...............................................................E.....................................................................................................................................................................................................................c:\documents and settings\factory\projects\comtypes\comtypes\tools\codegenerator.py:477: UserWarning: Structure __MIDL_IOleAutomationTypes_0004: PACKING FAILED: total alignment (8/64)
  warnings.warn(message, UserWarning)
FF....F.F.............................................................................................................................................................................................................................................E.....................................................................................................................................................................................................................................................................................................F.........................................................................................................................................................................................................................................................................................................................................................FF..............................................................................................................................F......................................................F..........................................................................F..E......................................................................................................................................................................................................................................................................................................F.........................................................................................................................................................................................................
======================================================================
ERROR: test_1054 (__main__.Test)
test GetModule('C:\\Windows\\system32\\netprofm.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 415, in <module]]
]]>

  File "c:\documents and settings\factory\projects\comtypes\comtypes\__init__.py", line 330, in __setattr__
    self._make_specials()
  File "c:\documents and settings\factory\projects\comtypes\comtypes\__init__.py", line 385, in _make_specials
    class _(partial.partial, self):
  File "c:\documents and settings\factory\projects\comtypes\comtypes\partial.py", line 41, in __new__
    raise TypeError("%r already has %s" % (base, k))
TypeError: <class 'comtypes.gen._DCB00D01_570F_4A9B_8D69_199FDBA5723B_0_1_0.IEnumNetworks'> already has __iter__

======================================================================
ERROR: test_1469 (__main__.Test)
test GetModule('C:\\Windows\\system32\\sppcomapi.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 1167, in <module]]
]]>

  File "c:\documents and settings\factory\projects\comtypes\comtypes\__init__.py", line 330, in __setattr__
    self._make_specials()
  File "c:\documents and settings\factory\projects\comtypes\comtypes\__init__.py", line 385, in _make_specials
    class _(partial.partial, self):
  File "c:\documents and settings\factory\projects\comtypes\comtypes\partial.py", line 41, in __new__
    raise TypeError("%r already has %s" % (base, k))
TypeError: <class 'comtypes.gen._B0C2A63F_AFF8_40E3_B42D_8A542DC909EC_0_1_0.IEnumNetworks'> already has __iter__

======================================================================
ERROR: test_551 (__main__.Test)
test GetModule('C:\\Windows\\system32\\icardie.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 35, in <module]]
]]>

  File "c:\documents and settings\factory\projects\comtypes\comtypes\safearray.py", line 53, in _midlSAFEARRAY
    sa_type = _make_safearray_type(itemtype)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\safearray.py", line 87, in _make_safearray_type
    raise TypeError(itemtype)
TypeError: <class 'comtypes.safearray.LP_SAFEARRAY_c_ubyte'>

======================================================================
FAIL: test_1247 (__main__.Test)
test GetModule('C:\\Windows\\system32\\PortableDeviceApi.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 1871, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_1248 (__main__.Test)
test GetModule('C:\\Windows\\system32\\PortableDeviceClassExtension.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 989, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_1252 (__main__.Test)
test GetModule('C:\\Windows\\system32\\PortableDeviceTypes.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 118, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_1254 (__main__.Test)
test GetModule('C:\\Windows\\system32\\PortableDeviceWMDRM.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 340, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_1733 (__main__.Test)
test GetModule('C:\\Windows\\system32\\wiascanprofiles.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 830, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_316 (__main__.Test)
test GetModule('C:\\Windows\\system32\\DevicePairingHandler.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 299, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_317 (__main__.Test)
test GetModule('C:\\Windows\\system32\\DevicePairingProxy.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 113, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_431 (__main__.Test)
test GetModule('C:\\Windows\\system32\\EhStorAPI.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 1438, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_481 (__main__.Test)
test GetModule('C:\\Windows\\system32\\fundisc.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 1002, in <module]]
]]>

AssertionError: 8

======================================================================
FAIL: test_549 (__main__.Test)
test GetModule('C:\\Windows\\system32\\iassvcs.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 446, in <module]]
]]>

AssertionError: 4

======================================================================
FAIL: test_817 (__main__.Test)
test GetModule('C:\\Windows\\system32\\LocationApi.dll')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_createwrappers.py", line 46, in test
    comtypes.client.GetModule(fname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 112, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "c:\documents and settings\factory\projects\comtypes\comtypes\client\_generate.py", line 183, in _CreateWrapper
    exec code in mod.__dict__
  File "<string>", line 1305, in <module]]
]]>

AssertionError: 8

----------------------------------------------------------------------
Ran 1921 tests in 21.246s

FAILED (failures=11, errors=3)
```

**Comment by junkmd** [comment]
Many tests were improved in #298.
Most of this code is now outdated.

The test on `QuerySevice` has been skipped due to using IE.
However, I think that the title of this issue itself can be interpreted as resolved.

The `QuerySevice` test should be considered in the scope of #267.

@cfarrow 
if the issue remains, please re-open.
